[package]
name = "cranelift-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.1"
cranelift = "0.85.1"
cranelift-module = "0.85.1"
cranelift-jit = "0.85.1"
colored = "2.0.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["std","fmt"] }